### ISSUE TITLE
6주차 과제입니다

### ISSUE THREAD

**Issue by iamwouldyou** [yamoo9/FDC#10]
비슷하게는 되는데 똑같이 만들기는 정말 어렵네요!
항상 감사합니다 :)

https://iamwouldyou.github.io/IELTS/ielts.html
https://iamwouldyou.github.io/IELTS/IELTS.psd

**Comment by yamoo9** [comment]
안녕하세요 우주님 ^^
말씀하신 것처럼 **비슷하게는 되어도 완벽하게 똑같이 만들기는 참 어렵죠** ^^;
과제 올려주신 것 잘 봤습니다. 곳곳에 노력해주신 흔적이 엿보여 좋았습니다. 🥇 

그럼 과제 검토 하면서 확인한 몇 가지 이야기 드릴께요.

먼저 시각적으로 Vertical Rhythm이 잘 지켜지지 않았는데요 ^^;
이 부분은 추후 수정하셔서 리듬을 지켜주시면 좋을 거 같아요~

그리고 다소 문법 오류가 발견되었는데 이 또한 수정해 주셔야 겠죠? 

### 1. Error: The `center` element is obsolete. Use CSS instead.

`<center>` 요소를 사용하셨는데 이는 비 표준으로 표준 문법에 어긋나니 사용하지 않으셔야 해요.
이 요소는 과거에 사용되던 요소로 사용하면 안되는 요소이니 까요. ❌ 

#### 2. Error: End tag `h5` seen, but there were open elements.

`<h5>` 제목 요소는 `<a>` 요소 내부에 포함되면 안되요. 표준 문법을 준수해 봅시다 ^^
수업 때 정리하며 공부해봐요~


그리고 이미지 포멧 다시 한 번 확인해보세요 ^^;
이미지가 PSD와 달리 깨진 것처럼 보이는데요.
확인해보세요 ^^

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_124679/7ixb3y2wUULZra6SreGUJzOOuiKFqo/Would%2BYou%2BUniversity%2B%257C%2B%25EC%259B%2594%25EA%25B8%2589%25EB%25A3%25A8%25ED%258C%25A1%2B%25EC%25A7%2581%25EB%2594%25A9%25EC%259D%2598%2B%25EC%2595%2584%25EC%259D%25B4%25EC%2597%2598%25EC%25B8%25A0%2B%25EB%258F%2585%25ED%2595%2599%252F3%25EC%25A3%25BC%2B%25EB%25B2%25BC%25EB%259D%25BD%25EC%25B9%2598%25EA%25B8%25B0%25EB%25A1%259C%2B%25EC%2595%2584%25EC%25B9%25B4%25EB%258D%25B0%25EB%25AF%25B9%25EB%25AA%25A8%25EB%2593%2588%2B7.0%2B%25EB%25A7%259E%25EC%259D%2580%2B%25ED%259B%2584%25EA%25B8%25B0%2B2017-03-02%2B08-34-36.jpg?Expires=1488498154&Signature=fPwxoE5mBv-Hk3maD~P9Jk9n2IpWyszIH2wDVt-eDsdHiahSlMMYlKR2gfk3C-Vy4beJopjMpVwNO3TpJ6A7CFe2KDwh~OOcV6JwwfwhZ7rAytBmPdijhbahXff5~Ua-RjlU1FjaPvHnz~H3ogaYmn~ZLVH2E9K4wt-uewPBTgFKIbzpf17~4q7Qqk7z3wkNw2viuIpJw6jbMQcd-ZiwSsB39wW5IoSCihEYdtr6eG9ZrV-a-1gHtnErCgiYFXPjGFcZG5iqDwSFlTkO0luQf9ao~OdTXsihFBZ9apBO9o9XbqFxperAtV24k-cgKj1TFthew6qgPdq~U-zhgRRXzA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)
