### ISSUE TITLE
FDC 4기 김복은 DAY07 실습

### ISSUE THREAD

**Issue by beatrice51** [yamoo9/FDC#15]
[Button Design](https://beatrice51.github.io/DAY07/button-design/button-design.html)

안녕하세요.
윈도우에서 css 설계할 때는
버튼의 안쪽 글씨가 
'a' Element의 padding 상하값을 같게 주면 버튼 정중앙에 왔는데,
맥에서 보니 수업 때처럼 위치가 중앙보다 위로 올라가게 변하네여.. 
그래서 맥에서 중앙에 보이도록 padding의 상하값을 다르게 주었습니다.

고맙습니다.

**Comment by yamoo9** [comment]
안녕하세요 복은님 ^^
크로스 브라우징 테스팅도 더해주셨군요! 
깔끔하고 오류없는 과제 수행 Good! 😮 

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_124679/vYAqz65wbRpDM6P2h0GOmBlsAq7BkE/screencapture-beatrice51-github-io-DAY07-button-design-button-design-html-1488575885808.jpg?Expires=1488662491&Signature=JC8YkuHPAnPa6ja5zMRr55~DzE3oWohR0iy2xrpgBUQJQ7-59xuXDas77jtdGA3LCAHrG7Lv9wqd4eMlH~7Bbuz4FV4UzyZqEjOMQqA0ArWNESnmIsR-TpSY7zgIapGa886KpA1fwzK74wRZq5-DRLdmN3tJYZH4ljm1uJZy6-bGjt98SH15RaKNQwfz2ywHL-tUACa4WRM5CQH3hc2V1c0ewWdIFWfSe64ADNHnDx3gbWz1jYmFR9ve9pKFaxsvEAEWW4S5FK-GvAmDKBpU73uUIxeaZePpgS-DFEsIf273B1wKIYf3y3LbGXnf9j9hdwghhyrUmjCE6xnO7MNtBA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)
