### ISSUE TITLE
FrontEnd DAY_08 과제(김예진)

### ISSUE THREAD

**Issue by tatoruz** [yamoo9/FDC#17]
안녕하세요 김예진입니다.
8강 과제 올립니다.
확인부탁드립니다

과제를 수행하는 중에 궁굼 한 것이 있어 질문 드립니다.
참고사이트의 상단 gnb 영역을 보시면 FASHION/BEAUTY/LIVING 부분이 서로 가까운데
각 클래스에 마진 값을 주어서 임의로 영역을 붙이려고 하였으나 구현되지 않았습니다.
하위 메뉴랑 같이 통으로 잡혀있기 때문에 그런건지.. 궁굼합니다..

-과제 html 주소
https://tatoruz.github.io/DAY_08_homework/byredo/index.html

-참고사이트 주소
http://beauty.sivillage.com/display/brandAutoCategory?brndHallCd=BEBH001&brndDspCatNo=010000003451&listPagingType=&dspCatNo=010000002007&depth=1&productOrdCd=PP&currentPage=4&perPage=24&chkBrndCds=&chkSizeCds=&chkColorChipNos=&chkAttrCds=&filterOpenYn=&filterOpenGrp=&srchDateTime=&infwPathTp=BR&currentPage=3

감사합니다

**Comment by yamoo9** [comment]
안녕하세요 예진님.

아직 우리 수업에서 Layout을 다루는 기법 공부가 끝나지 않은 상태라서 참고 사이트와 같은 구현이 안되고 있는 겁니다.
Float, Position, Flexbox 등을 다 배우고 난 후라면 참고 사이트 처럼 구현이 가능하실 거에요 ^^
