### ISSUE TITLE
4기 김규리 과제입니다.

### ISSUE THREAD

**Issue by kyuree** [yamoo9/FDC#18]
https://kyuree.github.io/day8_homework/jejuolle.html

위 링크가 과제이구요. 
height 값은 사용하지 않는게 좋다고 말씀 하셨는데, 
li 속에 float 을 사용해서 작업을 할 시 height 값이 없으면 문제가 생기더라구요.
검색해보니까 float 을 해제하는 방법이 여러가지가 있긴 한 것 같은데 일단은 height 값을 넣어서 작업을 진행했습니다.

**Comment by yamoo9** [comment]
수업 시간에 float 해제 방법 4가지를 살펴 보시면 height를 부여하지 않고도 
콘텐츠 만큼 높이를 설정할 수 있을 거에요 ^^ 수업 시간에 다뤄보죠!
