### ISSUE TITLE
박진희 과제

### ISSUE THREAD

**Issue by verybusystudio** [yamoo9/FDC#21]
http://oddgallery.cafe24.com/test.html
운영중인 몰에 테스트 페이지 생성하여 제작해보았습니다

질문
 : li onclick 으로 링크 연결시 새탭으로 띄울 수 있나요?

**Comment by yamoo9** [comment]
네 onclick 으로 새 탭 연결 가능합니다. ^^ 수업 오셔서 물어보시면 가르쳐 드릴께요
