### ISSUE TITLE
선생님 질문있습니다~

### ISSUE THREAD

**Issue by starseeker38** [yamoo9/FDC#23]
안녕하세요. 은정희입니다.

디자인작업하여 퍼블리셔에게 넘길 시에
포토샵상에서 레이어와 폴더 명/ 단계를 정리 하는데요.
이 작업을 모든디자인작업이 끝난후에 하는것이 효율적인지
아니면 디자인작업을 하면서 레이어명과 폴더단계들을 정리하는것이 효율적인지 궁금합니다.

디자인변경 시 정리된 레이어들을 수정하기에 조금 복잡한 부분이 있어
효율적인 작업방식에 대해 의견부탁드리겠습니다!

감사합니다.

**Comment by yamoo9** [comment]
안녕하세요 정희님 😃 

효율성 높은 디자인 작업방식은 [그룹 레이어/일반 레이어] 이름을 정리하면서 
디자인하는 습관을 가지는 것이 나은 선택이라고 생각합니다. 

디자이너는 습관적으로 정리하는 습성을 가져야 합니다. 

비단 이 자질은 비주얼 디자이너에 국한되는 이야기가 아니라, 설계자(Designer)로서 
기획자, 디자이너, 개발자, 마케터 모두에게 해당되는 이야기입니다. 

자신의 업무에 프로 정신(professionalism)을 가진 사람이라면 
필수적으로 정리 능력을 갖추고 있습니다.

물론, **작업 먼저. 정리 나중.** 이란 선택도 있습니다만... 
제가 권장하고 싶은 방법은 **그 때, 그 때 수시로 정리.** 입니다. 🥇
