### ISSUE TITLE
FDC 4기 김태연 DAY10 과제

### ISSUE THREAD

**Issue by tykimdesign** [yamoo9/FDC#24]
# 배너만들기

**과제 제출합니다!** 

[원숭이 배너 따라하기](http://tykimdesign.github.io/day10_HW/banner.html)

**Comment by yamoo9** [comment]
태연님 주말 활용하여 과제 수행해주셨군요 👍 
배너 만들기를 통해 position 공부가 잘 수행되었을 거라고 봅니다 😄 

잘 해주셨는데 조금 더 해보시면 좋을 내용이 있어 코멘트 드릴께요~
`.topbanner` 요소에 `overflow`, `height` 값을 적용/수정하면 
PSD 파일처럼 고릴라의 다리를 감출 수 있을 거에요. ^^

아래 이미지를 참고하여 완성해보세요! 🥇 


<img src="https://d1ro8r1rbfn3jf.cloudfront.net/ms_124679/lEVTGr12KS8WUdDuUkzpNYigg4Mnls/Banner%2B2017-03-12%2B23-12-51.jpg?Expires=1489414435&Signature=hkThwK7KapEZP6y7C8sFmgJFgltDq7a3KiYSe1w1QlI85P00NoyouRUyyBDc8ycBC0TYODnFHUlIwj0QGPbEhrPn6NqvIDh0e4JQgnG2SvdjmVvy7yib8gj5u4qPgrzl-YTUIWZPaqclZtfGjZKNituJdYunQWLLGbXE2lR9oxyfDAsPppnUC14CKk5-CNO9J9g7~KBnh~Ei4QSi3YbENMd7dqEFVRYTZhJTudlBY9eadW10k~Y581qdf3XZNkWitpC9HnJJU-KyC9Xr5ZbdjT5Rwn1tdlWayYMQEpyCj41r9-TFyc3StlijfWvT~zJ5w~JqJ~C3paFS4qQGT3VPpw__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA">

**Comment by tykimdesign** [comment]
코멘트 감사합니다~ 방금전에 수정해서 적용했어요 :)
