### ISSUE TITLE
크롬 검사기에서 workspace 설정하기

### ISSUE THREAD

**Issue by eyeray** [yamoo9/FDC#25]
안녕하세요 선생님

질문드립니다. 
workspace 설정을 하려고 하는데 알려주신 대로 
소스탭에서 cloud 폴더에서 마우스 오른쪽 버튼을 눌러서 add folder to workspace로 만든 다음 
액세스 허용을 하면 주황색 폴더가 생긴후, 주황색 폴더의 고칠 파일을 선택후 마우스 오른쪽 버튼을 눌러서 Map to network resouce를 해주면 cloud 폴더가 사라지게 되면 성공이라고 하셨는데, 제 경우에는 여기까지 되는데 막상 파일을 수정을 하면 반영 되지가 않습니다. 노트북에서는 되는데, 회사 컴에서는 반영되지가 않습니다.  다른 설정 방법 있는건지, 하는 방법을 잘못 알고 있는건지 알고 싶습니다.

**Comment by yamoo9** [comment]
안녕하세요 ^^

말씀하신 대로 하면 워크스페이스 설정이 되어야 정상인데 작동이 안된다고 말씀주시니 
보다 자세한 확인이 필요해 보입니다. 몇가지 제약사항이 있긴한데 아래 내용에 해당되시나요?

작업 영역은 매우 강력한 도구이지만, 여러분이 알아야 하는 몇 가지 제한 사항이 있습니다.

- Elements 패널에서 적용한 스타일 변경만 적용 가능.
- 외부 CSS 파일에서 정의한 스타일만 저장 가능.
- Elements 패널에서 적용한 스타일 변경은 명확히 저장하지 않아도 즉시 지속.
- 파일을 로컬 서버 대신 원격 서버로부터 매핑하는 경우, 페이지를 새로 고치면 
  Chrome이 해당 페이지를 원격 서버에서 다시 로드.
- 브라우저에서 매핑된 파일의 전체 경로를 사용해야 함.

---

설정 방법은 아래 링크 글을 통해 읽어보시고 
다시 한 번 확인해 보시길 바랍니다. ^^

[DevTools 작업 영역을 사용하여 지속성 설정](https://developers.google.com/web/tools/setup/setup-workflow)

**Comment by eyeray** [comment]
감사합니다. 
확인해보고 설정을 다시 해봤는데 화면에 바로 적용 되지는 않고,
파일을 에디터로 열어보면  저장이 될때도 있고 안될때도 있습니다. 
그래서 그냥 에디터로 하고 있습니다
