### ISSUE TITLE
FDC 4기 김예진 DAY10 과제

### ISSUE THREAD

**Issue by tatoruz** [yamoo9/FDC#28]
안녕하세요 김예진입니다.
과제 수행하여 올립니다
확인부탁드립니다

[과제1:영화포스터](http://tatoruz.github.io/DAY_10_homework/wall-e/wall-e.html)
ㄴ노트북에서 확인하실 때 화면에 가득차서 안 나오더라구요! 
   크롬 환경설정에서 화면을 50%줄여서 봐주세요..

[과제2:Banner-assets](http://tatoruz.github.io/DAY_10_homework/Banner-assets/Banner-assets.html)

여쭤볼게있는데요!
애니메이션 효과를 주었는데 시작점이 박스 밖일 경우 안보이게 가릴 방법이 없을까요~?
감싸고있는 class="banner"에 display:hidden으로 주었는데 적용이 안되어서 여쭤보아요!

**Comment by yamoo9** [comment]
오!!! 월E 멋진데요!!! 이펙트 조금만 더 줘볼께요 수업 시간에 ^^

그리고 배너는 애니메이션 처리 될 때 숨겨져야 할 영역이 보이는데
보이지 않게 바꿔봅시다 ^^

**Comment by tatoruz** [comment]
감사합니다! 수정했어요!~~
https://tatoruz.github.io/DAY_10_homework/Banner-assets/Banner-assets.html
