### ISSUE TITLE
질문드립니다~!

### ISSUE THREAD

**Issue by starseeker38** [yamoo9/FDC#3]
선생님 이번 과제 중
2 번째 과제는 자유롭게 한페이지를 디자인하고 html/css작업하는건가요~?

그리고 css를 따로 분리하지 않고
html내 에서 작성시와 css를 따로 분리했을 때
작성 위치만 다를 뿐
css 작성방식은 모두 같다고 생각하면 되는지 궁금합니다

감사합니다.

**Comment by yamoo9** [comment]
안녕하세요 @starseeker38 :-)

과제는 배운 타이포그래피를 토대로 Page Design 하나 만들어 보시고, HTML/CSS로 스타일링 해보시면 되요.
그리고 CSS는 HTML 문서 내에 포함해도 되고, 외부에 분리하셔도 되요 ^^
