### ISSUE TITLE
배너 애니메이션 과제 _서범석

### ISSUE THREAD

**Issue by eyeray** [yamoo9/FDC#33]
[배너애니메이션과제](https://eyeray.github.io/banner/banner2.html)

**Comment by yamoo9** [comment]
**와우**!

마지막 텍스트 떨어질 때 Wiggle 이펙트 좋네요!! 👍 
멋집니다 :-)

**Comment by yamoo9** [comment]
영상 링크 주소입니다. ^^
https://youtu.be/0lHHLI26N7k
