### ISSUE TITLE
DAY10 배너 실습

### ISSUE THREAD

**Issue by beatrice51** [yamoo9/FDC#34]
안녕하세요.
전에 작업한 일러스트 오브젝트를 활용해서 
배너 작업해보았습니다.
머리 속 상상은 쉬운데 
직접 옮기려니 어렵고 여기까지 하는데 엄청 오래 걸리네요.
애니메이션은 천천히(...) 넣어볼 예정입니다.

고맙습니다.
[배너만들기](beatrice51.github.io/DAY10/02/banner-training.html)
(참고로, 웹폰트가 로컬에서 작업할 때는 보이다가.
업로드하니 안보이네요. 이유는 모르겠어요. )

**Comment by yamoo9** [comment]
오오!
귀엽고 앙증맞은 토끼가! 요리를 하는 배너 ^^

**Cooking Rabbit**

Animation도 넣어서 보여주세요 (기대)

그리고 멋진 작품 완전해질 수 있게!
[문법 검사 결과](https://validator.w3.org/nu/?doc=https%3A%2F%2Fbeatrice51.github.io%2FDAY10%2F02%2Fbanner-training.html) 확인하신 후, 수정해주세요 그럼! 💯점
