### ISSUE TITLE
Frontend 4기 김현정 10일차 Poster 과제 제출

### ISSUE THREAD

**Issue by roscoe11** [yamoo9/FDC#36]
<작업물>
https://roscoe11.github.io/DAY10/homework-day10/homework-day10.html

<원본이미지>
https://roscoe11.github.io/DAY10/images/little_miss_sunshine-784110764-large.jpg

애니메이션은 추후에..죄송합니다..ㅠ ㅠ 일이랑 같이 하려니 힘드네요..
작업물 타이틀 부분을 언더라인에 맞추고 싶은데 어떻게 해야할까요?ㅠㅠ

**Comment by yamoo9** [comment]
안녕하세요 현정님 ^^

position을 사용해서 맞춰보시면 좋을 거 같네요~

수업 시간에 이야기 드려볼께요!

---

![](http://i68.tinypic.com/whebee.png)
