### ISSUE TITLE
선생님 수업 외 질문이 있는데요

### ISSUE THREAD

**Issue by tatoruz** [yamoo9/FDC#37]
안녕하세요 김예진입니다
지금 프론트엔드 4기 수업을 듣고 있는데요
프론트엔드/프론트엔드 개발 스쿨의 차이가 궁굼합니다
자바스크립트랑 제이커리 부분을 더 깊이배우는 건가요~?

**Comment by yamoo9** [comment]
안녕하세요 예진님 😃 질문에 답변드릴께요. 

[Front-End Develop SCHOOL](http://www.fastcampus.co.kr/dev_school_fds/) 과정은 [Front-End Design CAMP](http://www.fastcampus.co.kr/dev_camp_dfep/)와 차이가 있습니다.

첫째로, 스쿨 과정은 전일제 4개월 교육 과정으로 오전부터 밤 늦게까지 불철주야 공부에 매진하여 능력을 극대화하는 과정입니다. 이직/취직을 고려하거나, 커리어 전향을 꿈꾸는 이들을 위한 하드 트레이닝 코스에요. 반면 캠프는 저녁부터 밤까지 주 1~2회 가량 시간 내어 공부하는 재직자 대상 과정입니다.

두번째로, 스쿨 과정은 개인 작업 뿐만 아니라 팀 단위 학습을 지향하며 협업/팀웍 향상을 목표로 조직적인 개발 방법론을 추구합니다. 반면 캠프 과정은 팀 단위 학습 진행하기 어려우며 개인 학습 위주로 진행됩니다.

세번째로, 스쿨 과정은 Back-End과 Front-End 협업 프로젝트를 목표로 결과를 내며, 하이어링데이를 거쳐 자신이 갈고 닦은 능력을 검증 받아 하고 싶은 일을 할 수 있도록 도와주는 프로그램입니다. 반면 캠프 과정은 업무에 필요한 능력을 향상시켜주는 것을 목표로 하는 과정입니다.

![Fingo](https://media.giphy.com/media/l0IyoELV3cBEjLB1S/giphy.gif)
> Front-End Develop SCHOOL 2nd 기수 프로젝트 결과물: Fingo 영화 검색 사이트
