### ISSUE TITLE
FDC 4기 김복은 DAY12 내용 실습

### ISSUE THREAD

**Issue by beatrice51** [yamoo9/FDC#41]
[PSD](https://github.com/beatrice51/beatrice51.github.io/blob/master/DAY12/training/broadway_box__wireframe.psd)

[HTML](https://beatrice51.github.io/DAY12/training/training/grid-system.html)

**Comment by yamoo9** [comment]
깔끔하고 좋습니다. 👍 
수업 때 이야기 드린 부분을 잘 적용하셨네요! ^ㅡ^ 수고 많으셨어요!
