### ISSUE TITLE
김규리 14일차 과제 - YOUYU.com

### ISSUE THREAD

**Issue by kyuree** [yamoo9/FDC#43]
https://kyuree.github.io/day14/YOUYU.COM/index.html 

지난주 YOUYU 퍼블리싱한 내용입니다. 
수업하면서 디자인 작업이 미흡했던 부분 psd 수정해서 작업했습니다. 
(상단 필터 부분 레이어 부분, 로그인 레이어 부분,  언니의 팁 캐러쉘은 적용되지 않았습니다. ;;;)

질문1.  제품 리스트에서 좋아요 부분 코딩이 좀 헷갈립니다. 
제품 전체를 클릭했을때는 제품리스트로 이동이 되어야하고, 좋아요 (하트 아이콘) 부분을 클릭했을때는 좋아요가 적용되는 식으로 하려고 하는건데..
회사 퍼블리셔분이 작업하신거 보고, 좋아요 부분을 <i></i>를 사용해서 퍼블리싱 하긴 했는데요.. 이게 맞는건지 잘 모르겠어요.

질문2. 베스트리뷰에 별점 부분 코딩쪽이 제가 원하는 대로 코딩을 할수가 없네요.. ;;
제가 생각하기엔 첫번째 별위로 마우스가 올라오면, 첫번째 별만 색상이 변하고, 
두번째 별 위로 마우스 위로 올라가면 첫번째 부터 두번째 별까지 색상이 변해야 하고, 
세번째는 세번째별까지 색상이 변하는 식으로 되는게 맞을 것 같은데.. 이런식으로 코딩하려면 어떤식으로 해야하는지 잘 모르겠어요.. 

네이버 영화 별점 주는 부분 참고..  
http://movie.naver.com/movie/bi/mi/point.nhn?code=136872&onlyActualPointYn=Y#pointAfterTab

**Comment by yamoo9** [comment]
오우! 수고하셨어요 규리님 ^0^ 

질문 1에 대한 내용은 수업 시간에 모두와 함께 이야기를 나눠볼 께요
그리고 질문 2는 JavaScript를 사용하셔야 합니다. 상태(`State`)를 기억해야 하기 때문이에요.
