### ISSUE TITLE
선생님 고대비? 관련 질문 있습니다.^^;;

### ISSUE THREAD

**Issue by hw0507** [yamoo9/FDC#45]
프론트앤드 캠프 4기 수업 들었던 이혜원 입니다.

배경 이미지가 랜덤하게 바뀌면서 텍스트가 잘 보이게 텍스트 색이 자동적으로 변경되게 해야 하는데요;;;
명도 대비 수치값 같은거.... 그런거 아는게 하나도 없어서요....
참고할 사이트나.. 자료.. 뭐 없을까요???

**Comment by yamoo9** [comment]
안녕하세요 혜원님 ^^

WCAG 2.0 1원칙 **"인식의 용이성"** , 3지침 **"명료성"** 에 해당되는 질문 이네요.
관련 자료는 아래 글을 읽어보시면 좋을 것 같습니다.

- [디자이너와 기획자가 고려해야 할 웹접근성](http://darum.daum.net/accessibility/intro/wa)
- [WCAG 2.0 지침이 전하는 전경색과 배경색의 명도 대비](http://naradesign.net/wp/2009/07/01/947/)
- [WCAG 2.0: 글꼴색과 배경색 명도 대비 적합성 수준](http://naradesign.net/open_content/reference/contrastRatio.html)
