### ISSUE TITLE
FrontEnd 4기 신유민 과제제출 

### ISSUE THREAD

**Issue by YuminS** [yamoo9/FDC#6]
Medical View 과제제출합니다
https://github.com/YuminS/yumins.github.io/tree/master/DAY5/practice

**Comment by yamoo9** [comment]
유민님 ^^ 과제 수행 해주신 결과 확인했습니다. 👍 🥇 
**수고하셨어요!**

한가지 수정하면 좋을 것은 아래 링크 따라 가면 `&` 기호는 특수문자라서 `&amp;`로 변경해주시면 좋을 거 같아요 😸 
https://github.com/YuminS/yumins.github.io/blob/master/DAY5/practice/practice.html#L55
