### ISSUE TITLE
한지영

### ISSUE THREAD

**Issue by physiohan** [yamoo9/FDC#62]
https://github.com/physiohan

**Comment by yamoo9** [comment]
확인했습니다 ^^

**Comment by physiohan** [comment]
안녕하세요 선생님 한지영입니다. 어제 강의 너무 잘들었습니다.
회사 컴퓨터로 프로그램을 설치해봤는데 버벅거리네요..
Github프로그램에서 어제 만든 계정으로 로그인한 것 같은데 이 상태가 되었습니다 다음엔 뭘 해야하는지 모르겠네요..;
ㅜㅜ 답변부탁드려용~~ ^^


[image: 본문 이미지 1]



2017-05-17 0:08 GMT+09:00 Jee Hoon <notifications@github.com>:

**Comment by yamoo9** [comment]
안녕하세요 지영님 이미지가 안 떠서 그런데.. 문제는 해결 되셨나요?

**Comment by physiohan** [comment]
다른컴퓨터에서 원래있던 계정주소로 못들어가고있습니당... 출근해서 다시 해보려합니다

ai파일은 뜨나요?

2017. 5. 18. 오전 7:56에 "Jee Hoon" <notifications@github.com>님이 작성:

**Comment by yamoo9** [comment]
이 곳에 이미지를 보여주려면 온라인 상에 이미지를 올린 후에 이미지 링크 주소를 얻어야 합니다.

무료 이미지 호스팅 서비스를 하는 https://ko.imgbb.com/ 이 곳에 접속하셔서 이미지를 업로드 한 후,
이미지 주소를 GET 하세요. 그리고 나서 아래와 같은 문법을 사용하시면 이미지가 이 곳에 표시 됩니다.

```md
![이미지설명](이미지경로)
```

지영님 프로필 이미지를 예로 들어보면 아래와 같이 사용할 수 있습니다.

```md
![한지영](https://image.ibb.co/cMVeY5/han.jpg)
```

결과는 아래 이미지처럼 표시됩니다. 👌 

![한지영](https://image.ibb.co/cMVeY5/han.jpg)

**Comment by physiohan** [comment]
예감사합니다 해보겠습니다😊😊

2017. 5. 18. 오전 8:12에 "Jee Hoon" <notifications@github.com>님이 작성:

**Comment by physiohan** [comment]
선생님, 오늘과제 커밍순페이지의 이미지 인줄알았습니다 저 내용은 처음 질문드린 내용과 똑같습니다 ^^ 
1. 제 과제는 제 계정 주소에 있습니다. 제출은 어떻게 하는건가요? 선생님께서 조회하시는건가요?
2. Visual Studio Code 에서 기존 홈페이지의 ftp연결은 못하는건가요? 기존홈페이지를 연결해서 사용하려면 어떻게 해야하나요?

**Comment by yamoo9** [comment]
과제는 어제 확인했습니다 ^^
FTP 연결 부분은 수업 때 이야기 해볼께요~
