### ISSUE TITLE
질문있습니다~!

### ISSUE THREAD

**Issue by haha7** [yamoo9/FDC#67]
제가 수업중에 놓친 부분이 있어서요..ㅠ
1. 과제 알려 주시면서 보여주신 이미지 사이트 url 부탁 드립니다.
2. .md 라는 확장자를 가지는 파일은 html과 어떤 것이 다른가요? 또 #, ##, ###, [], () 은 .md 라는 파일에서만 사용 가능한건가요?? 
3. 강의할 때 쓰신거 같은데 비주얼스튜디오 에서 다른 선언들 말고 주석 달때 Emmet도 알려주세요~
4. 수업중에 쓰신 seo 체크하는 확장 프로그램 알려주세요~ 

수업 종료 후 바쁘신거 같아 여기에 글 남겨요~ㅎ ^^

**Comment by yamoo9** [comment]
#### 질문에 답변드립니다 ^ㅡ^

1. [unsplash.com](https://unsplash.com/) 입니다.
1. 네 맞습니다. Markdown 이라는 문서 포멧이 `.md`이고 `#`, `[]()` 등은 Markdown에서만 사용합니다.
1. Emmet은 수업 때 사용하면서 설명 드릴께요. 수업 때도 질문 많이 주세요~ 😃 
1. 파이어폭스 애드온인 [SenSEO](https://addons.mozilla.org/en-US/firefox/addon/senseo/) 입니다.
