### ISSUE TITLE
선생님~~

### ISSUE THREAD

**Issue by physiohan** [yamoo9/FDC#68]
여기서 탭이 먹히지 않는 이유가 뭐지요? ㅜㅜ 
이 편집기가 아닌가요?

![image](https://cloud.githubusercontent.com/assets/28730198/26145556/ceca567e-3b27-11e7-9de2-5726762bbebb.png)

그리고 혹시 만들어놓은 주소를 삭제하려면 어떻게 해야하나요? 
그리고 {계정주소}.github.io를 붙이고 안붙이고의 차이가 뭔가요?

![image](https://cloud.githubusercontent.com/assets/28730198/26145870/1d3dea18-3b29-11e7-812f-e0ef994510ee.png)

**Comment by yamoo9** [comment]
지영님 질문에 답변 드릴께요 ^^

먼저 Emmet에서 `!`를 입력하고, HTML 기본형 코드 스니펫(조각)을 출력 하려면 문서 포멧이 HTML이어야 합니다.
그러려면 문서의 확장자가 `.html` 또는 `.htm` 이어야 해요. 그런데 지금 이미지의 문서는 `.md` 확장자를 가진
Markdown 문서이기에 Emmet 코드가 적용되지 않는 거에요 ^^

————

그리고 저장소를 지우려면 아래 이미지를 참고하여 지우시면 되요.

### STEP 1. 
저장소 메뉴 Settings 클릭

![](https://preview.ibb.co/eMJeY5/01.jpg)

### STEP 2. 
Settings 페이지 Repository Name 복사

![](https://preview.ibb.co/mmKWfk/02.jpg)

### STEP 3. 
Settings 페이지 Danger Zone > Delete this repository 클릭

![](https://preview.ibb.co/fPoeY5/03.jpg)

### STEP 4. 
모달 창 메뉴에 저장소 이름 붙여넣고 I Understand the consequences, delete this repository 클릭

![](https://image.ibb.co/nMExLk/04.jpg)
