### ISSUE TITLE
FDC 4기 김복은 DAY06 실습

### ISSUE THREAD

**Issue by beatrice51** [yamoo9/FDC#7]
https://github.com/beatrice51/beatrice51.github.io/blob/master/DAY06/training/html/ticket_detail.html

인터파크 예매페이지 내용(width 값 700px)을 바탕으로 설계

**Comment by yamoo9** [comment]
복은님 예매 페이지 수행 결과 잘 봤습니다. 👩‍🚀 
시각적인 면에서 깔끔하고 정갈하게 잘 수행해주셨어요! 🍰 

그런데...

문법 적인 면에서는 몇 가지 오류가 발견 되었는데요. ^^;;
이 문제를 해결하면 보다 좋은 결과로 완성될 거에요!

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_124679/CFul4ZUbhVyyIYlfE5n4scjgTT07sx/Showing%2Bresults%2Bfor%2Bcontents%2Bof%2Btext-input%2Barea%2B-%2BNu%2BHtml%2BChecker%2B2017-03-02%2B07-58-13.jpg?Expires=1488495507&Signature=QaUlwnli04iKpVAXcfBWmwQeDRkR8wYpv2aJ~evH55WPkLxhLPmZl5GbkpdyYaDEz9UcikcONOmbFAKC3Csj1kqcEvjbq4LJcvXYdf02NDz89~Rdt8Nx04fi24ScpXFyrfiO-TZwc3~TDGe-OQf-Sfb9WeFlZinMJeMAVt5K9AmAc4VkuDicSLkhBQQuzACB~AW27U6ODe2Aw8hUaP1i4xMm~Mq5viriVCImd2vOKErtiyc6AxGDGozor-HnEFj~K8BDT3sfmP-E9iWli4xbCCMM4ONHkYE2SAvOTRX53zKRsPbYK1zzmNq9CsQvJFWUrjFjy6ZLxlNC53~7KTxDNA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)



문법적인 문제에서 몇 가지 이야기 드려보면

#### 1. [ERROR] The element h5 must not appear as a descendant of the dt element.

`<h5>`, `<h6>` 같은 제목 요소는 `<dt>` 정의 용어 요소 내부에 자식 요소로 사용될 수 없어요. 

#### 2. [ERROR] Bad character `레` after `<`. Probable cause: Unescaped `<`. Try escaping it as `&lt;`.

`<레드북>`에서 `<`, `>` 기호는 특수 문자라서 `&lt;`, `&gt;`라고 적어주셔야 해요 ^^
`<여신님이 보고 계셔>`, `<로렐라이 언덕>`도 마찬가지에요~ 

그럼 코멘트 확인하고 문제되는 부분을 수정해보세요~ 수고하셨습니다. 😃
