### ISSUE TITLE
과제 올리는거 질문드려요

### ISSUE THREAD

**Issue by ms733** [yamoo9/FDC#70]
선생님,
과제 올리라고 하신거
폴더생성하는 법을 몰라서
파일 업로드로 올라갔는데

이미지파일을 업로드 할때도 
깃허브 데스크탑 통해서 올렸어야 되는건가요??

처음 써봐서 어려워요 ;; ㅜ ㅜ

**Comment by yamoo9** [comment]
로컬 저장소(내 컴퓨터)에 폴더를 추가한 다음 이미지를 폴더에 넣으면
자동으로 GitHub Desktop에서 이를 감지 추적해서 화면에 보여줘요 ^^

Commit 후에 Sync 하면 원격 저장소(온라인 GitHub)에 그대로 올라가요.
내일 수업 때 보여드릴께요.
