### ISSUE TITLE
숙제 업로드합니다.

### ISSUE THREAD

**Issue by h1255pm** [yamoo9/FDC#71]
안녕하세요. 첫 번째 수업 과제 업로드합니다. 하루 늦었지만...
[h1255pm.github.io/hw/index.sketch](url)
이렇게 하는 게 맞나요?

확인 부탁드려요. 감사합니다!

**Comment by yamoo9** [comment]
아래 주소에 올리셨습니다. ^^

https://github.com/h1255pm/h1255pm.github.io/blob/master/hw/index.sketch
