### ISSUE TITLE
포토샵에서 파일만들때 96ppi로 쓰면 어떤변화가 생기나요?

### ISSUE THREAD

**Issue by eunsollee** [yamoo9/FDC#72]
수업중에 96ppi로 설정하고 시작하셨는데 
저는 72로밖에 안 해봐서요 ~ 
검색을 해서 글을 읽어봐도 정확하게 이해가 안가네요 
72에 맞춰 작업한 프로젝트를 96으로 바꾸게되면 폰트나 이미지 사이즈에 혼선이 올것 같은데
이부분 궁금합니다~!

**Comment by yamoo9** [comment]
다음 주 수업 때 자세한 이야기 드리겠지만, 생각하시는 것만큼 혼란스럽지 않습니다.

비트맵 이미지, 벡터 그래픽의 경우 72PPI, 96PPI에 영향을 받지 않아요.
영향을 받는 것은 글자 크기(Font Size)에요. 단, pt 크기가 영향을 받고, px은 영향을 받지 않아요.

웹 환경을 디자인한다면 웹 브라우저에서 처리되는 PPI가 96임을 알아두셨으면 하기에 
다음 시간 자세한 이야기 드릴 겁니다 ^^
