### ISSUE TITLE
버전 관리 질문드려요

### ISSUE THREAD

**Issue by h1255pm** [yamoo9/FDC#73]
안녕하세요.

어제 수업중에, 디자이너가 그래픽 파일 버전 관리를 할 때,
가장 나쁜 방식이 새로운 파일을 계속 생성해가면서 관리하는 거라고 말씀하셨는데요.
(파이널_1.psd, 파이널_2.psd 같은..)

그럼 디자이너의 파일 관리 - 스케치나 psd같은 - 도 github를 이용해 관리하나요?

**Comment by yamoo9** [comment]
네 ^^ GitHub으로 디자이너 파일 버전 관리가 가능합니다.
관련 글 링크 추가하니 읽어보세요~

- [디자이너를 위한 Git 사용법](https://brunch.co.kr/@ultra0034/55)
- [디자이너에게도 github 같은 버전관리시스템이 필요하다](https://blog.illustudio.co.kr/2017/02/18/%EB%94%94%EC%9E%90%EC%9D%B4%EB%84%88%EC%97%90%EA%B2%8C%EB%8F%84-github-%EA%B0%99%EC%9D%80-%EB%B2%84%EC%A0%84%EA%B4%80%EB%A6%AC%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%9D%B4-%ED%95%84%EC%9A%94%ED%95%98%EB%8B%A4/)


## 버전 관리란?
버전 관리란 무엇이며, 왜 이것을 알아야 할까? 

**버전 관리 시스템은 파일의 변화를 시간에 따라 기록하여 
과거 특정 시점의 버전을 다시 불러올 수 있는 시스템이다.** 

**이미지나 레이아웃을 수정할 때마다 각각의 형태를 모두 보존하고 싶은 
그래픽 디자이너나 웹 디자이너라면 버전 관리 시스템(VCS)을 사용하는 것이 현명할 수 있다.** 

VCS를 사용하면 **개별 파일 혹은 프로젝트 전체를 이전 상태로 되돌리거나 
시간에 따른 변경 사항을 검토할 수 있으며, 문제가 되는 부분을 누가 마지막으로 수정했는지, 
누가 언제 이슈를 만들어냈는지 등을 알 수 있다.** 

또한 **파일을 잃어버리거나 무언가 잘못되어도 대개 쉽게 복구할 수 있다.** 
그리고 이 모든 장점을 누리는 데는 큰 노력이 들지 않는다.

**아래와 같이 파일 관리하는 사태가 안생기를 바랍니다.**

```
abc_1102.psd
abc_1102_최종.psd
abc_1102_최종_1.psd
abc_1102_최종_2.psd
abc_1102_최종_final.psd
abc_1102_최종_final_1.psd
abc_1102_최종_final_1_이게_최종_마지막.psd
abc_1102_최종_final_1최종_완성본_1103.psd
abc_1104.psd
```
