### ISSUE TITLE
프로그램관련 질문있습니다~~

### ISSUE THREAD

**Issue by physiohan** [yamoo9/FDC#74]
스케치가 웹디자인에 최적화된 프로그램이라고 하셨는데, 찾아보니 맥용 프로그램이더라구요.
윈도우 사용자들은 스케치를 이용 못하나요?

**Comment by eunsollee** [comment]
현재는 안되는걸로 알고있습니다~

**Comment by physiohan** [comment]
그렇군요 아쉽습니당............

**Comment by yamoo9** [comment]
은솔님 말씀대로에요 ;;
