### ISSUE TITLE
주소설정 질문드립니다.

### ISSUE THREAD

**Issue by physiohan** [yamoo9/FDC#75]
![image](https://cloud.githubusercontent.com/assets/28730198/26235015/854502a6-3ca3-11e7-95d3-7d294601eefa.png)

질문내용은 형광펜 칠한 부분입니다.
저 주소를 눌러도 서버를 찾지 못합니다.
주소가 잘못된건가요?

**Comment by yamoo9** [comment]
https://physiohan.github.io/

위 주소로 접속해보세요 ^^

**Comment by physiohan** [comment]
이 페이지가 아니라 phistudy.github.io 이게 떠야하는뎅.... 
![image](https://cloud.githubusercontent.com/assets/28730198/26240831/5d7d1b90-3cbd-11e7-8f41-898375aab70c.png)
다시한번 봐주시겠어요? ㅜㅜ

**Comment by yamoo9** [comment]
GitHub Page 서비스는 계정 이름과 동일한 `github.io` 주소만 허용합니다.
사용하시는 계정 이름이 `physiohan` 이기 때문에 http://phistudy.github.io 는 작동하지 않습니다.
http://physiohan.github.io 만 사용 가능하세요. 다른 github.io 주소는 작동하지 않습니다. ^ㅡ^

**Comment by physiohan** [comment]
어머나 그렇군요! 감사합니다 ㅎㅎ
