### ISSUE TITLE
선생님 질문있습니다.

### ISSUE THREAD

**Issue by lioliolio** [yamoo9/FDC#76]
1. 선생님께서 이미지 리사이즈 할때 사용하시는 툴은 어떤건가요? 궁금합니다.

2. 1366x768 해상도일 때 이미지 크기는 해상도와 비슷하게 맞추면 되는건가요? 아니면 다른 기준이 있나요?

**Comment by yamoo9** [comment]
안녕하세요 ^^
질문에 답변 드려봅니다.

### 1. 이미지 사이즈 크기 변경

일반적으로는 Adobe Photoshop 에서 하고 있어요.

Photoshop이 없거나, 크기 조정하는데 Photoshop 처럼 무거운 앱 구동이 부담되는 경우에는
OSX 기본 앱인 `미리보기.app`를 구동하여 크기를 조정하기도 해요. ^^

<img src="https://preview.ibb.co/k6VcoF/2017_05_22_3_27_19.png" alt>

### 2. 이미지 해상도

질문이 정확히 이해가 안가는데... 만약 이미지 크기를 말하는 거라면, 
기본 x1 배율인 스크린에서 이미지 해상도는 예전처럼 디자인과 같이 하면 되요 ^^

배율이 x1 이상일 경우는 배율에 맞춰야 하지만요.
자세한 내용은 수업 때 차차 다뤄볼 겁니다~
