### ISSUE TITLE
sketch 사용에 대한 질문(고민)

### ISSUE THREAD

**Issue by makershin** [yamoo9/FDC#77]
안녕하세요.
5기 신지나입니다.
강사님께서 강의시간에 sketch에 대해서 언급하시는것을 들으면서 
sketch를 써보고싶다는 생각이 들었습니다. 

유료 프로그램이여서 주저되는것도 있지만,
제가 고민하는 포인트는 
sketch를 사용해본적이 없어서 인터페이스와 기능들을 익히지 못한 상태인데
수업에서 요구하는 과제들을 바로 sketch를 사용해서 수행 할 수 있을까?에 대한 것입니다.
- 아무래도 sketch에 대한 별도의 개별적인 학습이 필요한가요?
- 아니면 스케치가 포토샵과 일러의 툴과 비슷하거나 혹은 UI자체가 심플해서 익히기 쉬운 프로그램일까요?

바쁘시겠지만, 답변을 주시면 큰 도움이 될 것 같습니다^^

**Comment by yamoo9** [comment]
안녕하세요 지나님 ^^

Sketch는 매우 사용법이 쉬운 UI 제작 도구입니다. 

반면 Adobe Photoshop은 이미지 편집 및 제작 도구이지, UI 디자인에 최적화된 도구는 아닙니다.
그래서 Adobe도 Sketch와 유사한 Experience Design CC 제품을 별도로 개발 중입니다. (현재 Beta)

제가 사용해 본 Sketch는 디자이너라면 금새 익힐 수 있습니다.
사용법이 단순하고, 벡터 기반의 툴이라 매우 깔끔합니다. (Photoshop은 픽셀 기반)
Photoshop, Illustrator 보다 가볍고, 파일 크기 또한 작습니다. (Photoshop은 비대해지죠...)
특히 Symbol(재사용 가능한 컴포넌트 기능)로 유지보수 및 관리가 용이합니다.

NAVER나, Kakao 에서도 Sketch를 사용하고 있는데 이유는 다 있는 거죠 ^^

Sketch는 분명 쉽지만, 그럼에도 약간의 학습은 필요합니다.
하지만 Photoshop을 배우는 것만큼의 학습 시간은 필요하지 않아요.
Photoshop은 너무 기능이 많아요 ^^;;;

Sketch 하루 정도 사용해보면 금새 익힐 수 있을 겁니다.
생각보다 쉬워서 놀라실지도 ^ㅡ^
