### ISSUE TITLE
섹션에 대한 질문

### ISSUE THREAD

**Issue by sp2armint** [yamoo9/FDC#78]
안녕하세요, 야무선생님.

어제 수업 중에

'눈에 보이지만 섹션에 대한 제목이 필요한데 그것은 장애인을 위한 것이다.
보이지 않는 영역을 위한 설계가 필요하다.' 

이렇게 말씀을 해주셨습니다.

눈에 보이지 않는 부분의 섹션을 위한 <제목>이라는 것이 어디에 들어가는 것인지 잘 모르겠어요.

**Comment by yamoo9** [comment]
## 각 섹션(Section)은 섹션을 대표하는 적절한 제목이 요구됩니다.

섹션에 제목이 필요한 이유는 사람 또는 로봇(검색엔진, 스크린리더 등) 등이 
콘텐츠를 인식하고 이해할 수 있어야 하기 때문입니다.

UI 디자인에서 항상 섹션마다 제목을 시각적으로 표시하지 않지만,
구조 상으로는 제목을 소유해야 합니다.

이에 대한 근거로는 웹 표준과 접근성 준수 사항에서 찾을 수 있습니다.
먼저 섹션 요소 내부에 제목이 없을 경우, 문법 검사 과정에서 경고합니다.

#### 표준 문법 검사 결과 경고 메시지

<img src="https://preview.ibb.co/bM48DF/2017_05_24_11_03_20.png" alt>

#### 접근성 가이드라인 WCAG2

[<img src="https://preview.ibb.co/bw5b0v/2017_05_24_11_08_01.png" alt>](https://www.w3.org/TR/WCAG20-TECHS/H69)

**Comment by sp2armint** [comment]
제 질문이 너무 빈약했던 것 같습니다.
다시 적어볼게요 :-)


어제 네이버의 디자인을 벗기셨을 때, 텍스트만 있던 화면을 기준으로 여쭈어 볼게요.

로고가 들어가는 자리, 메뉴가 들어가는 자리 등 그 각각의 자리를 저는 섹션으로 이해했습니다.

그리고 그 각 섹션에 제목을 지어주어야 한다고 이해했습니다.
로고가 들어가는 자리에는 <logo>, 메뉴가 들어가는 자리에는 <menu> 이런 식으로요.

위의 첨부 이미지로 '**섹션에 대한 이름을 지어주는 방법**'을 제가 이해하기로는 
**h1 ~ h6  을 통해** 직접적으로 보여지든 보여지지 않든 css에서 코딩을 해 두어야 한다는 말씀으로 들리는데
이렇게 이해하는 것이 맞는지 궁금합니다.

직관적으로 **섹션에 대한 이름을 지어준 예시 코딩**의 스크린샷으로 알려주시면 이해하기 쉬울 것 같아요.
이런 코드가 있는데 어떤 부분이 섹션에 대한 '이름'을 지어준 예시이고 이렇게 보이고
장애인들이 실질적으로 사용했을 때 들리는 '그 이름'을 지어준 예시이다 하고요.

**Comment by yamoo9** [comment]
넵 직관적인 이해를 위한 이미지 첨부 드려요 ^ㅡ^ 

<img src="https://preview.ibb.co/dZ4GYF/NAVER_2017_05_24_12_58_00.jpg" alt="NAVER_2017_05_24_12_58_00" border="0">
