### ISSUE TITLE
몇가지 질문 드립니다!

### ISSUE THREAD

**Issue by jin-lab** [yamoo9/FDC#79]
**1. UI Kit를 만드는 시간은 어느 정도 걸리나요?**

저는 프리랜서로 에이전시와 조인해서 대기업 웹/앱 구축 디자인을 하고 있습니다.
보통 대표화면의 시안 2~3 타입 제작 후 스타일 가이드를 만들면서 동시에 서브 페이지를 진행하는데요,
스타일 가이드를 완벽하게 설계하고 디자인을 진핼 할 수 있는 일정과 환경이 아닙니다.
커머스나 금융 분야의 사이트는 볼륨이 크고 복잡해서 UI Kit 설계를 금방 할 수 없고,
완벽하게 만들고 들어갈 정도로 여유도 없습니다.
일정이 촉박해 기획, 디자인, 퍼블리싱이 동시에 진행되는 경우도 많고요.

**2. HTML의 타이틀이 6단계인 이유는 무엇인가요?**
- '약관' 컨텐츠 디자인 할 때 뎁스가 많아지는 것 빼고 웹사이트를 구축 할 때 6단계까지 필요하지 않은 경우가 많습니다.
- 기획이 완료되지 않은 상태에서 디자인을 진행하는 경우가 많은데, 전체 페이지가 나오지 않은 상태에서 타이틀의 단계를 설계 할 수 있나요?

**3. 포토샵의 툴바나 패널의 위치를 변경한 워크스페이스 설정 상태를 저장해서 다른 사람에게 공유할 수 있나요?**

**4. 포토샵은 신규 레이어가 위로 쌓이는 방식인데요, 아래로 생기게 할 수 있나요?**

**5. 웹/앱 UI 요소의 용어를 잘 정리해 놓은 곳이 있을까요?**

실무를 하다보면 기획자, 디자이너, 퍼블리셔가 각자 똑같은 요소를 다르게 말하거나,
야매로 용어를 쓰는 경우가 많습니다. 뭐라고 불러야 할지 모르는 요소들도 있고요.

**6. 야무님은 해외 디자인 프로세스를 어떻게 공부하셨나요?**

**Comment by yamoo9** [comment]
### 1. UI Kit를 만드는 시간은 어느 정도 걸리나요?

프로젝트 성향, 규모, 일정, 디자이너 설계(Design) 구현 수준(능력), 개발과 접점에 대한 이해/응용 능력, 모던 워크 플로우 경험 등등 워낙 변수가 많아 정확하게 얼마나 걸린다고 이야기 드리기 어렵습니다.

UI Kit에 관련되어 해외 사례는 많지만, 국내 사례는 찾아보기 힘든데요.(공개를 잘 안하죠) 티몬 크리에이티브센터가 작성한 [UI Kit 만들기가 그렇게 어렵나요?](https://brunch.co.kr/@creative/105) 글이 참고 되지 않을까 합니다. 

그리고 이 수업에서 다루는 디자인 방법론은 효과적인(검증된) 방법 중심으로 소개하는 과정으로, 전문적으로 숙달하여 활용하려면 학습 시간과 경험이 요구됩니다. 당연하게도 숙달되지 않으면 어색하고, 의문이 갈 수 있습니다. 

말씀하신 것처럼 기존 프로세스의 경험의 잣대에서 UI Kit 방법론을 보면, '저게 가능할까?' 의문이 들게되는 점 이해합니다. 하지만, 다른 관점에서 기존 프로세스를 보면 과연 설계(Design)의 본질적 의미에 대해 이해하고 프로젝트를 진행하고 있는가 물어보고 싶습니다. 

수시로 바뀌는 기획과 디자인 시안이 나오기 전까지 개발은 아무 것도 할 수 없는 직렬식 프로세스가 얼마나 비 효율적이고, 비 생산적인지 반성해야 하지 않을까요? 문제가 있다면 문제의 원인은 파악하고 개선해야할 노력이 필요하지 않을까 합니다.

이와 유사한 사례를 저는 교육을 통해 많이 경험했습니다. 대표적으로 이야기 드리면 다음과 같습니다.

1. 웹 표준을 왜 지켜야 하지? 그런거 업무에 아무 소용없다. -> 현재 웹 표준 준수 환경으로 변모
1. 접근성 준수가 꼭 필요해? 귀찮기만 하지... -> 접근성 보장 의무화. 법률 시행. (향후 법 준수 및 규제 강화)
1. ActiveX 사용, 공인 인증서 없이 어떻게 보안을 지키나? -> ActiveX 철폐, 공인이 아닌 인증서 규제로 변경

Jin-Lab 에서 이 교육을 통해 이야기 드린 방법론을 수용하느냐 아니냐의 문제는 제가 논할 문제는 아니라고 생각합니다. 이러한 프로세스와 시스템(체계)를 디자인 선진 환경에서는 왜 사용할까? 고민해주시고 봐주셨으면 좋겠습니다. 물론 수용에 관한 결정은 과정이 끝난 시점에 다시 생각해보셔도 좋지 않을까요? ^^

### 2. HTML의 타이틀이 6단계인 이유는 무엇인가요?

HTML 표준에서 제공하는 제목 단계가 6단계입니다. (정해진 문법 규칙입니다) 프로젝트에서 6단계까지 설계(Design)하고 안하고 와는 별개의 문제입니다. 그리고 jin-Lab 에서 자주 거론하는 **기획이 완료되지 않은 상태** 라는 것 자체가 **설계가 체계적이지 않다**, **문제를 수반한 프로세스를 하고 있다** 고 말하는 거라 봅니다.

설계를 사전에 할 수 있나요? 묻기 전에, **사전에 기획한 사항(Design)이 왜 변경되는 거지?**에 대한 의문이 먼저가 아닐까 합니다. ^^

### 3. 포토샵의 툴바나 패널의 위치를 변경한 워크스페이스 설정 상태를 저장해서 다른 사람에게 공유할 수 있나요?

Photoshop 자체 기능으로는 Workspace를 공유할 수 없습니다만, JavaScript를 사용하면 가능합니다. [Workspace import/export script for Photoshop](http://blogs.adobe.com/jnack/2010/05/workspace_importexport_script_for_photoshop.html) 글을 참고하셔서 [WorkspaceImportExport.jsx.zip](http://www.jnack.com/adobe/photoshop/cs5/WorkspaceImportExport.jsx.zip) 다운로드 받아 수업 시간에 ToggleGrid.jsx 설정 했던 것처럼 하면 사용하실 수 있습니다. ^^

### 4. 포토샵은 신규 레이어가 위로 쌓이는 방식인데요, 아래로 생기게 할 수 있나요?

Photoshop 에서는 Layer Stack 순서를 역순으로 변경하는 옵션을 제공하고 있지 않습니다. 레이어 순서를 연순으로 변경하고자 한다면, 변경하고자 하는 레이어 묶음을 선택한 후 `Layer` > `Arrange` > `Reverse` 명령을 실행하면 역순으로 변경됩니다. 이와 같은 일이 자주 수행된다면 단축키를 등록해서 사용하면 편리하게 사용하실 수 있을 거에요. ^^

<img src="https://preview.ibb.co/cdYHav/2017_05_29_8_45_06.png" alt="">

### 5. 웹/앱 UI 요소의 용어를 잘 정리해 놓은 곳이 있을까요?

웹, 앱은 서로 다른 분야이기에 용어 또한 다릅니다. 각 환경에서 사용하는 용어를 구분하여 전해야 상대방이 이해할 수 있을 거에요 ^^ 관련 글이 많지만, 아래 글이 도움이 되지 않을까 합니다.

- [UX 신입 디자이너가 알아야 할 UI디테일 용어](http://story.pxd.co.kr/616)
- [앱의 구성요소](https://brunch.co.kr/@flatdesign/2)

### 6. 야무님은 해외 디자인 프로세스를 어떻게 공부하셨나요?

해외 디자인 프로세스 아티클을 주로 살펴보고, 프로젝트, 교육 자료에 반영하고 있습니다. 저는 논리(Logic)를 선호하는 디자이너이자, 개발자로서 이해가 안되거나, 비효율적인 프로세스 보다는 효율적이고 생산적이며, 재사용 가능한 디자인 설계를 지향하고 있습니다. ^^
