### ISSUE TITLE
과제제출_타이포그래피_은정희

### ISSUE THREAD

**Issue by starseeker38** [yamoo9/FDC#8]
1. 치과
https://github.com/starseeker38/starseeker38.github.io/tree/master/DAY_6

2.자유주제(미완성입니다)
https://github.com/starseeker38/starseeker38.github.io/tree/master/study

**Comment by yamoo9** [comment]
정희님 수행해주신 과제 잘 봤습니다. ^^
자유 주제 멋지게 완성 하시길 응원합니다! 🏃‍♀️ 

먼저 자유주제인 **Cloud Service**는 문법적으로 문제가 없습니다.

하지만 안타깝게도 **치아 건강** 페이지는 다소 문법에 문제가 발견 되었는데요.
내용을 살펴보면 다음과 같습니다.

#### 1. Error: An `img` element must have an `alt` attribute, except under certain conditions.

아래 링크를 따라가면 `<img>` 요소에 `alt` 속성이 없는데 이는 **접근성** 준수에 있어 매우 중요한 이슈입니다.
**[장애인 차별 금지 법률 조항(장차법)](http://likms.assembly.go.kr/law/jsp/pop/EnfLawView.jsp?LAW_ID=A2047)에 따라 처벌 대상이 될 요인**이니 필히 대체 텍스트 작성을 습관화 해주세요 ^^

> **웹 콘텐츠 접근성 가이드라인 2.0**
>
> 원칙 1 **인식의 용이성**
> 지침 1-1 **텍스트가 아닌 콘텐츠는 적절한 대체 텍스트를 요구한다.**

https://github.com/starseeker38/starseeker38.github.io/blob/master/DAY_6/main.html#L18


#### Error: Stray end tag `a`.

다른 하나의 오류는 여는 태그`<div>`와 닫는 태그 `</a>`가 달라 발생한 문제입니다. ^^;
이 문제를 해결해주시면 더 좋은 결과가 되겠죠? ^0^ 

https://github.com/starseeker38/starseeker38.github.io/blob/master/DAY_6/main.html#L76
