### ISSUE TITLE
웹에디터 관련 질문드립니다 ^^

### ISSUE THREAD

**Issue by jin-lab** [yamoo9/FDC#80]
안녕하세요~ 야무 강사님!
웹에디터를 찾아보니까
비주얼스튜디오코드 말고도, 아톰이랑 서브라임텍스트를 많이 쓰는것 같은데요.
강사님께서 서브라임텍스트를 쓰시는 이유는 무엇인가요?
장점이 궁금합니다 ^^

**Comment by yamoo9** [comment]
안녕하세요 ^^ @jin-lab 님

Sublime Text 가 등장한 이후, 이와 유사한 UX를 가진 도구들이 연이어 등장했어요.
Bracket, Atom, Visual Studio Code 등이 그런 에디터 입니다.

저는 국내에 Sublime Text 가 알려지기 전부터 사용하고 있었어요.
그리고 [국내 사용자를 위해 영상 강의](https://goo.gl/LeRw3o)도 촬영하여 공개 했답니다. ^^

제가 그간 Sublime Text를 사용했던 이유는 다른 에디터가 Sublime Text를 따라 만들 정도로
잘 만들어지고, 가볍고 확장성 높다는 점을 높이 사서입니다. 그리고 다른 에디터에 비해 손에 익어 
익숙하고, 다양한 기능을 확장하여 사용하고 있다보니 선호하게 된답니다. 

**무엇보다 Atom, Visual Studio Code 도구보다 빠릅니다.**

하지만 최근에는 School 수강생의 강제(?)성 높은 요구로 Visual Stuio Code를 사용하고 있습니다.
이제 이 에디터도 손에 익어 익숙해졌어요 ^^ 도구는 역시 어디까지나 도구일 뿐. 익숙의 문제로 보입니다. ^ㅡ^
