### ISSUE TITLE
1.24 배율이 이해가 안되요 ㅠㅠ

### ISSUE THREAD

**Issue by hahayuni** [yamoo9/FDC#81]
강의 시간에 작업할때 1.24 배율로 h1 ~ h6 까지 폰트 크기를 정했는데요,
1.24로 배율을 정한 특별한 이유가 있는건가요 ?
아니면 1.24가 아닌 다른 비율로 작업을 해도 무관한건가요 ?

아래 내용을 봤는데 이해가 되지 않습니다. ㅠㅠ

타입 스케일 배율(Type Scale Ratio)
1.067 — Minor Second
1.125 — Major Second
1.200 — Minor Third
1.250 — Major Third
1.333 — Perfect Fourth
1.414 — Augmented Fourth
1.500 — Perfect Fifth
1.600 — Minor Sixth
1.618 — Golden Ratio (황금 비율)
1.667 — Major Sixth
1.778 — Minor Seventh
1.875 — Major Seventh
2.000 — Octave
2.500 — Major Tenth

**Comment by yamoo9** [comment]
배율은 이전 글자 크기 대비 비율로 디자이너가 설계 과정에서 찾아야 할 규칙입니다.
이 배율에 정답이 있는 것은 아니고 ^^ 여러 번의 시행착오 끝에 가장 적절한 비율을 찾는 것이 관건입니다.

제 경험으로는 황금 비율(1:1.618)은 글자 크기 대비가 심하게 커지고, 마이너 써드(1:1.2) 비율은 대비 차가
미미한 듯 하여 1.2 이상 1.4 이하에서 비율을 찾는 편이에요 ^^

프로젝트 성향, 사용자 분석을 통해 디자인(설계) 과정에서 디자이너가 찾아야 할 값이니,
값에 대한 암기 보다는, 적용을 통해 적절한 값을 찾아야 하는 시도에 대해 이야기 드리고 싶네요 ^^
