### ISSUE TITLE
유용한 포토샵 익스텐션이나 스크립트 아시면 소개 부탁드려요~!

### ISSUE THREAD

**Issue by eunsollee** [yamoo9/FDC#82]
포토샵을 사용하는데 계속 반복적인 노가다를 하고있는것같아서 ㅠㅠ 
이전 글에 링크되어있던 ink 라는 가이드 툴은 받아서 사용하고있고요. 

다른것들 찾아보니 cc2015 이상에서는 안되는 것들이 많드라구요. 

혹시 아시는것 있으시면 공유 부탁 드려요~!

**Comment by yamoo9** [comment]
안녕하세요 은솔님 ^^
유용한 Photoshop Extension 에 대해서는 수업 시간에 필요한 부분이 나올 때마다 소개하도록 할께요 :-)
