### ISSUE TITLE
포토샵에 toggle grid js 실행안되는 문제 캡쳐 올립니다~! 

### ISSUE THREAD

**Issue by eunsollee** [yamoo9/FDC#83]
![1](https://user-images.githubusercontent.com/28730194/27165335-465da97c-51ce-11e7-9d47-edf2f5ba173d.png)
![3](https://user-images.githubusercontent.com/28730194/27165334-4657730e-51ce-11e7-83ff-3c473bd0f224.png)

경로 제대로 찾아서 넣었다고 생각하는데
포토샵 메뉴에서 실행하면 저런 메시지가 뜨네요~!

**Comment by yamoo9** [comment]
수업 시간에 이야기 드린 것처럼 toggleGuude.jsx 다시 다운로드 받아 시도해보세요 ^^
