### ISSUE TITLE
목요일 수업 마지막에 디자인 파일 관련해서

### ISSUE THREAD

**Issue by lioliolio** [yamoo9/FDC#84]
목요일 수업 마지막에 보여주셨던 디자인 파일 가지고 복습을 하고 싶은데

깃헙에 올려주실수 있나요? ^^;;

**Comment by yamoo9** [comment]
넵 ^^ 아래 주소에 올려두었습니다. 수업 시간에 뵐께요~
https://goo.gl/YsT17a
