### ISSUE TITLE
단위변환, 웹폰트, 박스에 관하여

### ISSUE THREAD

**Issue by physiohan** [yamoo9/FDC#85]
안녕하세요 선생님 작업중에 헤메는 부분이 있어서 문의드립니다..

1. 단위변환 사이트
![image](https://user-images.githubusercontent.com/28730198/28047673-972d7f28-6626-11e7-95af-91452e9754d9.png)
여기서 기본단위가 16px이라고 나오는데 14px로 설정해야 하는지요?
아니면 저렇게 바꿔도 상관이 없나요? 기본값은 왜 다른가요?

2. 스포카 웹폰트를 사용하려고 하는데 thin을 적용하려면 어떤 코드가 필요한가요?
line-height로 적용이 안되는 것 같습니다..

3. 
![image](https://user-images.githubusercontent.com/28730198/28053073-8687e316-6649-11e7-898f-c25d01349ba0.png)
이것에 관한 코딩이 필요한 상황인데 맨 위에 네비게이션 부분을 박스 지정할 때 로고는 왼쪽으로가고 네비는 오른쪽으로 가야하는데 잘 안됩니다.. float속성으로 지정해야 할까요? position인가요?

강의때 따라해본거랑 직접 해보려니 잘 안되네요...... 흑ㅜㅜ

**Comment by yamoo9** [comment]
목요일 수업 때 좀 일찍 오시면 옆에서 알려드릴께요 ^^
글로 쓰기에는 질문이 방대해서 옆에서 설명하는 것이 좋을 것 같아요~

**Comment by physiohan** [comment]
예알겠습니다~~ ^^
