### ISSUE TITLE
멤버들과 공유~~

### ISSUE THREAD

**Issue by physiohan** [yamoo9/FDC#86]
선생님이 저희 연결해주신거처럼
계정을 직장동료들과 공유하려면 어떻게 해야하나요? 
그리고 현재 작업중인 홈페이지를 깃헙계정에 모두 연동할 수 있나요? 용량이 될런지..

**Comment by physiohan** [comment]
css구현 익스텐션 요청드립니다~~ ptjy88@naver.com으로 부탁드려요~~

**Comment by yamoo9** [comment]
@physiohan 메일로 보내드렸어요 ^^

그리고 GitHub 계정을 직장 내에서 공유하려면 협업(Collaboration) 설정을 해야 해요 
화요일 일찍 오시면 이야기 드릴께요 ^^

마지막으로 웹사이트 관리에 있어 GitHub 허용 용량은 현재 50MB 이상으로 PSD 파일과 같은 대용량 파일은 관리가 어렵습니다만, 방법이 없는 것은 아닙니다. 아래 링크 글을 따라가서 방법을 적용하면 50MB 이상의 대용량 파일도 관리가 가능해집니다.

[GitHub 대용량 파일 관리 방법](https://github.com/yamoo9/FDC/blob/master/5th/README/GitHub-lfs.md)
