### ISSUE TITLE
그리드 그릴때 스마트오브젝트 한개로 그리는 단축키 알려주세요.

### ISSUE THREAD

**Issue by hahayuni** [yamoo9/FDC#87]
그리드 그릴때 스마트오브젝트 한개로 그리는 단축키 알려주세요.
수업시간에 알려주셨는데 까먹었어요 ㅠㅠ

**Comment by yamoo9** [comment]
Path Layer 를 사용해서 그리시면 되요 ^^
단축키는 **A** (Path Selection Tool) 입니다.

---

<img src="https://preview.ibb.co/n75rzk/0.jpg" alt="0" border="0">

**Comment by hahayuni** [comment]
친절한 답변 감사합니다! ^^

2017-07-20 14:38 GMT+09:00 Jee Hoon <notifications@github.com>:
